package RPCprotocol;

public enum RequestType {
    LOGIN, LOGOUT,
    GET_BY_USERNAME,
    GET_ALL_MECIURI,
    ADD_TO_LOGGED_USERS,
    FIND_MECI_BY_ID,
    GET_LAST_FREE_ID_VANZARI,
    GET_TOTAL_BILETE_CUMPARATE_FOR_MECI,ADD_VANZARE,
}
